print(10/2)
print(10*2/3)
print(2+2*2)
print((2+2)*2)
print(5<3)
print(5==5)
print(7!=7)
print(9>=9)
print(3<=2)
print( (9==1) and ( 7>6 )      )
print( (9==1) or ( 7>6 )      )
print( not(3<=2)   )

print("hi my name is" + " Jeff")

# Boolean Algebra
print(False*False)
print(False and False)
print(True and False)
print(False or True)
print(True or not(False))
